do stuff with trust as well as pair/connect

diff --git a/bin/bluectrl b/bin/bluectrl
--- a/bin/bluectrl
+++ b/bin/bluectrl
@@ -25,6 +25,7 @@ function printusage {
     echo "    con|connect           pair/connect a device"
     echo "    dis|disconnect        disconnect a connected device"
     echo "    disall|disconnectall  disconnect all connected devices"
+    echo "    trust                 trust a device"
     echo "    reset                 reset bluetooth kernel module"
     echo ""
     echo "options:"
@@ -95,7 +96,7 @@ if [[ -z "$(cat $RAWIDFILE)" ]]; then
 fi
 
 for x in $(cat $RAWIDFILE); do
-    bluetoothctl info $x | grep -e "Device" -e "Alias:" -e "Paired:" -e "Connected:" | awk '/Device/ {id=$2;} /Alias:/ {match($0, /Alias: (.*)/, m);name=m[1]} /Paired:/ { paired=$2} /Connected:/ {connected=$2} END {printf("%s\t%s\t%s\t%s\n", id, paired, connected, name)}' >> $IDFILE
+    bluetoothctl info $x | awk '/Device/ {id=$2;} /Alias:/ {match($0, /Alias: (.*)/, m);name=m[1]} /Paired:/ { paired=$2} /Connected:/ {connected=$2} /Trusted:/ { trusted=$2} END {printf("%s\t%s\t%s\t%s\t%s\n", id, paired, connected, trusted, name)}' >> $IDFILE
 done
 
 bluetoothctl paired-devices | awk '{match($0, /Device ([^ ]+) (.*)$/, m); printf("%s\t%s\n", m[1], m[2])}' > $PAIREDFILE
@@ -103,38 +104,34 @@ bluetoothctl paired-devices | awk '{match($0, /Device ([^ ]+) (.*)$/, m); printf
 
 # do stuff
 if [ $# -eq 0 ] || [[ $1 == "info" ]]; then
-    if [ -z "$(cat $IDFILE | awk '$3 == "yes"' | cut -f 1,4)" ]; then
+    if [ -z "$(cat $IDFILE | awk '$3 == "yes"' | cut -f 1,4,5)" ]; then
         echo "no connected devices"
     else
         echo "connected devices:"
         OLDIFS="${IFS}"
         IFS=$'\n'
-        for x in $(cat $IDFILE | awk '$3 == "yes"' | cut -f 1,4); do
-            echo "    ${x}"
-        done
+        cat $IDFILE | awk -F\\t '$3 == "yes" { printf("    %s\t%s", $1,$5);if ($4 == "yes") { print "\t(trusted)"} else {print ""} }'
         IFS="$OLDIFS"
         echo ""
     fi
-    if [ -z "$(cat $IDFILE | awk '$2 == "yes" && $3 == "no" ' | cut -f 1,4)" ]; then
+    if [ -z "$(cat $IDFILE | awk '$2 == "yes" && $3 == "no" ' | cut -f 1,4,5)" ]; then
         echo "no paired but unconnected devices"
     else
         echo "paired but unconnected devices:"
         OLDIFS="${IFS}"
         IFS=$'\n'
-        for x in $(cat $IDFILE | awk '$2 == "yes" && $3 == "no" ' | cut -f 1,4); do
-            echo "    ${x}"
-        done
+        cat $IDFILE | awk -F\\t '$2 == "yes" && $3 == "no" { printf("    %s\t%s", $1,$5); if ($4 == "yes") { print "\t(trusted)"} else {print ""}}'
         IFS="$OLDIFS"
         echo ""
     fi
 
-    if [ -z "$(cat $IDFILE | awk '$2 == "no"' | cut -f 1,4)" ]; then
+    if [ -z "$(cat $IDFILE | awk '$2 == "no"' | cut -f 1,5)" ]; then
         echo "no unpaired devices"
     else
         echo "unpaired devices:"
         OLDIFS="${IFS}"
         IFS=$'\n'
-        for x in $(cat $IDFILE | awk '$2 == "no"' | cut -f 1,4); do
+        for x in $(cat $IDFILE | awk '$2 == "no"' | cut -f 1,5); do
             echo "    ${x}"
         done
         IFS="$OLDIFS"
@@ -143,10 +140,15 @@ if [ $# -eq 0 ] || [[ $1 == "info" ]]; then
 
 elif [[ "$1" == "con" ]] || [[ "$1" == "connect" ]]; then
 
+    if [ -z "$(cat $IDFILE | awk '$3 == "no"' | cut -f 5)" ]; then
+        echo "no unconnected devices. try --scan"
+        exit 0
+    fi
+
     echo "connect device:"
     OLDIFS="${IFS}"
     IFS=$'\n'
-    select DEVICE in $(cat $IDFILE | awk '$3 == "no"' | cut -f 4); do
+    select DEVICE in $(cat $IDFILE | awk '$3 == "no"' | cut -f 5); do
         break
     done
     IFS="$OLDIFS"
@@ -176,10 +178,15 @@ elif [[ "$1" == "con" ]] || [[ "$1" == "connect" ]]; then
 
 elif [[ "$1" == "dis" ]] || [[ "$1" == "disconnect" ]]; then
 
+    if [ -z "$(cat $IDFILE | awk '$3 == "yes"' | cut -f 5)" ]; then
+        echo "no connected devices."
+        exit 0
+    fi
+
     echo "disconnect device:"
     OLDIFS="${IFS}"
     IFS=$'\n'
-    select DEVICE in $(cat $IDFILE | awk '$3 == "yes"' | cut -f 4); do
+    select DEVICE in $(cat $IDFILE | awk '$3 == "yes"' | cut -f 5); do
         break
     done
     IFS="$OLDIFS"
@@ -190,9 +197,52 @@ elif [[ "$1" == "dis" ]] || [[ "$1" == "disconnect" ]]; then
     echo "done."
 
 elif [[ "$1" == "disall" ]] || [[ "$1" == "disconnectall" ]]; then
-    for x in $(cat $IDFILE | awk '$3 == "yes"' | cut -f 1); do
+    for x in $(cat $IDFILE | awk '$3 == "yes"' | cut -f 5); do
         bluetoothctl disconnect $x
     done
+
+elif [[ "$1" == "trust" ]]; then
+    if [ -z "$(cat $IDFILE | awk '$4 == "no"' | cut -f 5)" ]; then
+        echo "no paired, but untrusted devices."
+        exit 0
+    fi
+
+    echo "trust device:"
+    OLDIFS="${IFS}"
+    IFS=$'\n'
+    select DEVICE in $(cat $IDFILE | awk '$4 == "no"' | cut -f 5); do
+        break
+    done
+    IFS="$OLDIFS"
+
+    chosen_id=$(cat $IDFILE | awk '$4 == "no"' | tail -n+"$REPLY" | head -n1 | cut -f1)
+    if ! bluetoothctl trust $chosen_id > /dev/null; then
+        echo "failed to trust $DEVICE"
+        exit 1
+    fi
+    echo "done"
+
+elif [[ "$1" == "untrust" ]]; then
+    if [ -z "$(cat $IDFILE | awk '$4 == "yes"' | cut -f 5)" ]; then
+        echo "no trusted devices."
+        exit 0
+    fi
+
+    echo "trust device:"
+    OLDIFS="${IFS}"
+    IFS=$'\n'
+    select DEVICE in $(cat $IDFILE | awk '$4 == "yes"' | cut -f 5); do
+        break
+    done
+    IFS="$OLDIFS"
+
+    chosen_id=$(cat $IDFILE | awk '$4 == "yes"' | tail -n+"$REPLY" | head -n1 | cut -f1)
+    if ! bluetoothctl untrust $chosen_id > /dev/null; then
+        echo "failed to untrust $DEVICE"
+        exit 1
+    fi
+    echo "done"
+
 elif [[ "$1" == "reset" ]]; then
     # sometimes bluetooth gets into a bad state
     # this lets us completely reset it
